### ISSUE TITLE
Would be great with some integration tests

### ISSUE THREAD

**Issue by Nicoolai** [LEGO/kong-aws-request-signing#22]
**Is your feature request related to a problem? Please describe**

Even if the plugin builds, I have no idea if it actually works when loaded into Kong.  

**Describe the solution you'd like**

Automated integration testing in the build pipeline.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by hafstroem** [comment]
Hey @Nicoolai 
I added some integration tests here: https://github.com/LEGO/kong-aws-request-signing/pull/43
They will test the validity of the signature created and also the effect of a few of the configuration options.
Can we close this issue?

**Comment by Nicoolai** [comment]
> Hey @Nicoolai I added some integration tests here: #43 They will test the validity of the signature created and also the effect of a few of the configuration options. Can we close this issue?

Absolutely :)
