### ISSUE TITLE
Publishing to luarocks

### ISSUE THREAD

**Issue by Nicoolai** [LEGO/kong-aws-request-signing#23]
**Is your feature request related to a problem? Please describe**

It would be nice if the plugin was on luarocks and could be easily installed using `luarocks install`

**Describe the solution you'd like**

Should we do this? Is it a good idea to have it in luarocks?

**Describe alternatives you've considered**

Alternative is to not do it, leave things as is.

**Additional context**

N/A

**Comment by fczuardi** [comment]
it is possible to install from source pointing here to github, the README includes it on the instructions, the only problem is that the current .rockspec file is stating a version for which there is no branch/tag here on the main repo

I have created a fork with the proper branch and was able to install it with:

```
luarocks install https://raw.githubusercontent.com/marmotitude/kong-aws-request-signing/main/kong-aws-request-signing-1.0.3-3.rockspec
```

**Comment by DanielRailean** [comment]
closing as the plugin can now be installed by using:

```sh
luarocks install https://github.com/LEGO/kong-aws-request-signing/raw/main/kong-aws-request-signing-1.0.4-3.rockspec
```

or 

```sh
luarocks install https://github.com/LEGO/kong-aws-request-signing/raw/main/rocks/kong-aws-request-signing-1.0.4-3.all.rock
```
