### ISSUE TITLE
Use aws-request-signing in combination with other kong plugins, such as canary release

### ISSUE THREAD

**Issue by CNorskov** [LEGO/kong-aws-request-signing#40]
**Is your feature request related to a problem? Please describe**
I would like to be able to do canary release with lambdas, and direct a given percentage to one url, and another to the default.

**Describe the solution you'd like**
I would like to be able to specify which lambda url to hit for a given endpoint/path/method for the canary specifications.

**Describe alternatives you've considered**
Not using canary deployments, but do full traffic to one alias url, and then rollback manually (or implement auto rollback down the line).

**Additional context**
The canary deployment is possible with AWS Gateway for lambdas, and in general is possible with kong. But not in combination with this plugin.

This is the canary plugin in question:
https://docs.konghq.com/hub/kong-inc/canary/

**Comment by hafstroem** [comment]
Adressed this issue in this PR: https://github.com/LEGO/kong-aws-request-signing/pull/41
